# Generated by Django 6.0.2 on 2026-02-09 09:00

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='downloads_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='expires_at',
            field=models.DateTimeField(default=files.models.default_expiry),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='max_downloads',
            field=models.IntegerField(default=1),
        ),
    ]
