# Generated by Django 6.0.2 on 2026-02-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_sharedfile_downloads_used_sharedfile_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
