# Generated by Django 6.0.2 on 2026-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_sharedfile_otp_code_sharedfile_otp_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='encrypted_data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='filename',
            field=models.CharField(default=b'', max_length=255),
            preserve_default=False,
        ),
    ]
