# Generated by Django 6.0.2 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_sharedfile_file_sharedfile_encrypted_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_token', models.UUIDField()),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.CharField(max_length=50)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
