# Generated by Django 6.0.2 on 2026-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_sharedfile_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='verified_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
