# Generated by Django 6.0.2 on 2026-02-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_sharedfile_otp_created_at_sharedfile_verified_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
