# Generated by Django 6.0.2 on 2026-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_sharedfile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
