# Generated by Django 6.0.2 on 2026-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_sharedfile_blocked_until_sharedfile_failed_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlog',
            name='file_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
