# Generated by Django 6.0.2 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_downloadlog_file_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
