# Generated by Django 6.0.2 on 2026-02-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_downloadlog_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlog',
            name='username',
        ),
    ]
