# Generated by Django 6.0.2 on 2026-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_remove_downloadlog_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='verified_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
