# Generated by Django 6.0.2 on 2026-02-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_sharedfile_verified_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='sender_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
